Hexa-Coders-aug23/product_catalog

- .eslintrc.js
- src/modules/shared/components/header/Header.module.scss
Fixes VSCode problem with linter on Windows
> font-color changed, fix VSCode tslint

- src/modules/NotFoundPage/NotFoundPage.module.scss
- src/modules/NotFoundPage/NotFoundPage.tsx
https://prnt.sc/i9mSKRx0Y1qB
https://prnt.sc/WfMSJL6YGFJh
https://prnt.sc/3pFV-NJ5SSfr
> add not found page

- src/api/phones.ts
- src/modules/CatalogPage/CatalogPage.module.scss
- src/modules/CatalogPage/CatalogPage.tsx
- src/modules/shared/components/Card/Card.tsx
- src/modules/shared/components/ProductsList/ProductsList.module.scss
- src/modules/shared/components/ProductsList/ProductsList.tsx
- src/modules/shared/components/ProductsList/index.ts
- src/styles/blocks/_container.scss
- src/styles/blocks/_grid.scss
- src/types/Phone.ts
- src/utils/fetchClient.ts
Fetching phones data
I will customize selects in my next PR
> Load phones from api

- src/modules/shared/components/footer/Footer.module.scss
- src/modules/shared/components/footer/Footer.tsx
- src/modules/shared/components/header/Header.tsx
change links
add target=blank
add id to header for "back to top" button
little change in header for linter
> fix footer, little change header

- src/modules/FavouritesPage/FavouritesPage.module.scss
- src/modules/FavouritesPage/FavouritesPage.tsx
Desktop: https://prnt.sc/vHszbm5HAHR2
Tablet: https://prnt.sc/UFajuNy8CZgO
Mobile: https://prnt.sc/oUP2fa4G4LHU
> add favourites page

- src/Root.tsx
- src/modules/AccessoriesPage/AccessoriesPage.module.scss
- src/modules/AccessoriesPage/AccessoriesPage.tsx
- src/modules/AccessoriesPage/index.ts
- src/modules/TabletsPage/TabletsPage.module.scss
- src/modules/TabletsPage/TabletsPage.tsx
- src/modules/TabletsPage/index.ts
https://www.loom.com/share/38511c057e91496dacc349bc609ab080?sid=7258471d-f5a5-4acb-b9d8-8eedea479b79
> add tablets/accessories pages and routes for them

- src/modules/CatalogPage/CatalogPage.module.scss
- src/modules/CatalogPage/CatalogPage.tsx
- src/modules/shared/components/Loader/Loader.module.scss
- src/modules/shared/components/Loader/Loader.tsx
- src/modules/shared/components/Loader/index.ts
Please, reuse this Loader component for loading your cards and provide an amount of loading ones
> add loader

- src/api/favoritePhones.ts
- src/modules/FavouritesPage/FavouritesPage.module.scss
- src/modules/FavouritesPage/FavouritesPage.tsx
- src/styles/blocks/_container.scss
https://www.loom.com/share/a2fa62b9d55748908063020173652c56?sid=af0061ff-dd8a-4022-896e-b4a0bab398c3
Also, fixed padding-top in main container from 40px to 24px(40px copied from landing page)
> render favorites from localstorage

- src/modules/CatalogPage/CatalogPage.module.scss
- src/modules/CatalogPage/CatalogPage.tsx
- src/modules/shared/components/Breadcrumbs/Breadcrumbs.module.scss
- src/modules/shared/components/Breadcrumbs/Breadcrumbs.tsx
- src/modules/shared/components/Breadcrumbs/index.ts
- src/modules/shared/components/CustomSelect/CustomSelect.tsx
- src/modules/shared/components/Pagination/Pagination.module.scss
- src/modules/shared/components/Pagination/Pagination.tsx
- src/modules/shared/components/ProductsList/ProductsList.module.scss
- src/types/Breadcrumb.ts
Please, reuse this Breadcrumbs component on your pages with providing own breadcrumbs arrays for maping
> Breadcrumbs

- src/modules/CatalogPage/CatalogPage.tsx
Simple fix for correct displaying of perPage = 'all'
> fix all perPage

- src/modules/shared/components/burger/Burger.tsx
- src/modules/shared/components/burger/BurgerMenu.module.scss
- src/modules/shared/components/header/Header.module.scss
- src/modules/shared/components/header/Header.tsx
fixed shift up when select tab, made black underscore before element
added circle count for favorites and cart
> Header count circles

- src/modules/shared/components/footer/Footer.module.scss
- src/modules/shared/components/footer/Footer.tsx
Made all Back to top button interactive
> made back to top clickable and add hover effect

- src/modules/shared/components/Card/Card.module.scss
- src/modules/shared/components/Card/Card.tsx
- src/modules/shared/components/ProductsList/ProductsList.tsx
Open product page when click on card photo or its title, didn't make all the card clickable, because of unpredictable work of interactive elements in card (add to cart and like works incorrect).
> open product page on card click

- package.json
- src/Root.tsx
- src/api/auth.ts
- src/context/AuthProvider.tsx
- src/modules/LoginPage/LoginPage.module.scss
- src/modules/LoginPage/LoginPage.tsx
- src/modules/LoginPage/index.ts
- src/modules/RegisterPage/RegisterPage.module.scss
- src/modules/RegisterPage/RegisterPage.tsx
- src/modules/RegisterPage/index.ts
- src/modules/shared/components/CustomSelect/CustomSelect.tsx
- src/modules/shared/components/RequireAuth/RequireAuth.tsx
- src/modules/shared/components/RequireAuth/index.ts
- src/types/Login.ts
- src/types/Register.ts
- src/types/User.ts
- src/utils/accessTokenService.ts
- src/utils/authClient.ts
Please fix tokens implementation and use logic from RequireAuth on making purchase
Now you can get the access to login and register pages via /login and /sign-up path
> Auth content

- src/modules/PhonePage/PhonePage.module.scss
- src/modules/PhonePage/PhonePage.tsx
> need to fix and separate

- src/context/GlobalProvider.tsx
- src/modules/CartPage/CartPage.tsx
- src/modules/CartPage/Modal/Modal.tsx
https://www.loom.com/share/4cab0caa24964e64a9a40c7290c35a8f?sid=7df2040d-e3da-489c-b227-0fbe0dd06165
> add login logic to cart

- src/modules/HomePage/HomePage.module.scss
- src/modules/HomePage/components/Banner/BannerSlider.module.scss
- src/modules/HomePage/components/Banner/BannerSlider.tsx
- src/modules/HomePage/components/BannerSection/BannerSection.module.scss
- src/modules/HomePage/components/BannerSection/BannerSection.tsx
- src/modules/HomePage/components/CategoriesSection/CategoriesSection.module.scss
- src/modules/PhonePage/PhonePage.module.scss
- src/modules/shared/components/ProductsSliderLib/ProductsSlider.module.scss
- src/modules/shared/components/ProductsSliderLib/ProductsSlider.tsx
tiny changes to make buttons accurate width. HomePage centered due to model
> banner button change

- src/modules/HomePage/HomePage.tsx
- src/modules/shared/components/ProductsSliderLib/ProductsSlider.module.scss
- src/modules/shared/components/ProductsSliderLib/ProductsSlider.tsx
- src/modules/shared/components/ProductsSliderLib/SliderLoader/LoaderCard.module.scss
- src/modules/shared/components/ProductsSliderLib/SliderLoader/LoaderCard.tsx
- src/modules/shared/components/ProductsSliderLib/SliderLoader/index.ts
https://www.loom.com/share/47e1d4a47bc840f2b88ee5ca3cf88f46
> add loader on slider and fixed title wrap

- src/modules/CartPage/CartPage.module.scss
> small fixes

- src/modules/shared/components/footer/Footer.tsx
> footer nesting structure

- src/Root.tsx
- src/context/AuthProvider.tsx
- src/modules/AccountPage/AccountPage.module.scss
- src/modules/AccountPage/AccountPage.tsx
- src/modules/AccountPage/index.ts
- src/modules/CartPage/CartPage.tsx
- src/utils/http/httpClient.ts
https://www.loom.com/share/5bfa4db03dd946c9ad76e6892b0d6b9e
> Account page
